### ISSUE TITLE
Github says '400 bad request'

### ISSUE THREAD

**Issue by bigfatbird** [flattr/osd-flattr-chrome-extension#5]
I don't know if this is temporarily - didn't use the plugin for a while.

**Comment by pthulin** [comment]
When does GitHub say that?

**Comment by bigfatbird** [comment]
Is this because a flattrplugin isn't connected to a flattruser? I click with the chromeextension https://chrome.google.com/webstore/detail/opjnhfkbdoopgfbefgbdkpjnbghffmln on a rep. and github serves the 400-site.

**Comment by pthulin** [comment]
Thanks for your help, the problem should be resolved now in v0.8.5 of the extension.

**Comment by bigfatbird** [comment]
Works fine.
