### ISSUE TITLE
Option to not automatically send all URL visited to Flattr

### ISSUE THREAD

**Issue by thiloplanz** [flattr/osd-flattr-chrome-extension#7]
Right now, the plugin sends all URL you are visiting to Flattr, even if you have no intention to flattr them.

This makes for better usability, because the Flattr button will only be shown if the Flattr supports the site, but comes at the cost of severe privacy invasion and wastes network resources.

There could be an option to show the button always, and only when pressed contact Flattr.

**Comment by voxpelli** [comment]
Wouldn't the extension then work very much like the official bookmarklet that can be found on http://flattr.com/extension - why not instead use the bookmarklet then?

**Comment by smgt** [comment]
If you are concerned with the privacy the bookmarklet is the option. I'm closing this issue.

**Comment by chpio** [comment]
sorry for commenting on an old thread... but... i can't find the bookmarklet anywhere. https://flattr.com/extension responds with a 404, so no luck there.
